# Global gas settings and EIP-1559-like fee mechanics (BTC-denominated)
mode: stochastic   # deterministic | stochastic

# Single global stochastic adjustment applied to all primitives' gas at the high of band:
# adjusted_gas = max(gas_low, gas_high * (1 + draw)), truncated to [gas_low, gas_high]
gas_adjustment:
  mu: -0.10
  sigma: 0.05
  min: -0.30
  max:  0.10
  truncation: truncnorm
  seed: 11

# EIP-1559-like effective price in BTC per gas: base_fee_t + priority_tip_btc
# base_fee_t evolves lognormally (mu_bf, sigma_bf); priority_tip is constant for simplicity
eip1559:
  base_fee_btc_start: 1.0e-8    # in BTC/gas (example)
  mu_bf: 0.00
  sigma_bf: 0.10
  priority_tip_btc: 1.0e-9      # BTC/gas
  seed: 12
