# Non-rebasing stBTC (price-per-share). 50% of BTC fees accrue to assets.
supply_start: 300        # Format: 100_000. Initial circulating supply of stBTC tokens
exch_rate_start_btc: 1.0        # Initial price-per-share versus BTC
fee_share_to_stbtc: 0.50        # Fraction of protocol BTC fees accruing to stBTC

flows:
  assets_rate:                  # Growth/decay in underlying BTC assets backing token
    mode: stochastic            # stochastic => draw each period; deterministic => use mu
    mu: 0.50                    # Mean per-period rate (pre-truncation)
    sigma: 0.15                 # Std dev of rate (pre-truncation)
    min: -0.1                  # Lower clamp for draw
    max:  0.30                  # Upper clamp for draw
    truncation: truncnorm       # Distribution type for truncation
    seed: 41                    # RNG seed for assets rate

  supply_rate:                  # Net token supply expansion/contraction rate
    mode: stochastic            # Mode controlling randomness
    mu: 0.1                    # Mean supply rate
    sigma: 0.02                 # Std dev of supply rate
    min: -0.30                  # Minimum realized draw
    max:  0.10                  # Maximum realized draw
    truncation: truncnorm       # Distribution / truncation scheme
    seed: 42                    # RNG seed for supply rate
