# Canonical EVM-style tx types used on Botanix (fees paid in BTC)
tx_types:                              # Canonical transaction categories and cost multipliers
  native_transfer: {baseline_multiplier: 1.00}        # Simple value transfer baseline
  erc_transfer:    {baseline_multiplier: 1.05}        # Token transfer overhead
  contract_creation: {baseline_multiplier: 1.10}      # Deployment slightly higher base
  contract_call:   {baseline_multiplier: 1.20}        # Generic contract invocation heavier
